services:
  docsmatic:
    image: ghcr.io/nusephived/docsmatic:latest
    container_name: docsmatic
    restart: no
    networks:
      - apps
    environment:
      - TZ=Europe/Paris
      - AB_USERNAME=${AB_USERNAME}
      - AB_PASSWORD=${AB_PASSWORD}
      - NC_USERNAME=${NC_USERNAME}
      - NC_PASSWORD=${NC_PASSWORD}

networks:
  apps:
    external: true