services:
  docsmatic:
    image: ghcr.io/nusephived/docsmatic:latest
    container_name: docsmatic
    restart: no
    networks:
      - apps
    environment:
      - TZ=Europe/Paris
      - AB_USERNAME=${AB_USERNAME}
      - AB_PASSWORD=${AB_PASSWORD}
    volumes:
      - "/tank/apps/nextcloud/data/hugobsh/files/Archives/Fiches de paie/AlphaOmega:/docsmatic/docs/salary/AlphaOmega:rw"

networks:
  apps:
    external: true