name: Build & publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        run: |
          docker build . -t ghcr.io/nusephived/docsmatic:latest
          docker push ghcr.io/nusephived/docsmatic:latest